/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookAVisitRouteImport } from './routes/book-a-visit'
import { Route as InvestmentRouteImport } from './routes/investment'
import { Route as RoiCalculatorRouteImport } from './routes/roi-calculator'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookAVisitRoute = BookAVisitRouteImport.update({
  id: '/book-a-visit',
  path: '/book-a-visit',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentRoute = InvestmentRouteImport.update({
  id: '/investment',
  path: '/investment',
  getParentRoute: () => rootRouteImport,
} as any)
const RoiCalculatorRoute = RoiCalculatorRouteImport.update({
  id: '/roi-calculator',
  path: '/roi-calculator',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book-a-visit': typeof BookAVisitRoute
  '/investment': typeof InvestmentRoute
  '/roi-calculator': typeof RoiCalculatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book-a-visit': typeof BookAVisitRoute
  '/investment': typeof InvestmentRoute
  '/roi-calculator': typeof RoiCalculatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book-a-visit': typeof BookAVisitRoute
  '/investment': typeof InvestmentRoute
  '/roi-calculator': typeof RoiCalculatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/book-a-visit' | '/investment' | '/roi-calculator'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/book-a-visit' | '/investment' | '/roi-calculator'
  id: '__root__' | '/' | '/book-a-visit' | '/investment' | '/roi-calculator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookAVisitRoute: typeof BookAVisitRoute
  InvestmentRoute: typeof InvestmentRoute
  RoiCalculatorRoute: typeof RoiCalculatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-a-visit': {
      id: '/book-a-visit'
      path: '/book-a-visit'
      fullPath: '/book-a-visit'
      preLoaderRoute: typeof BookAVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment': {
      id: '/investment'
      path: '/investment'
      fullPath: '/investment'
      preLoaderRoute: typeof InvestmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roi-calculator': {
      id: '/roi-calculator'
      path: '/roi-calculator'
      fullPath: '/roi-calculator'
      preLoaderRoute: typeof RoiCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookAVisitRoute: BookAVisitRoute,
  InvestmentRoute: InvestmentRoute,
  RoiCalculatorRoute: RoiCalculatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
